# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('revspeed', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
