# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_usb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usb',
            old_name='revspeed',
            new_name='readspeed',
        ),
    ]
